android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official

# Увеличиваем оперативную память для самого Gradle
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError

# Включаем параллельную сборку для ускорения
org.gradle.parallel=true

# Выделяем отдельную память для сборщика ресурсов Android (D8/R8)
android.useDexArchive=true
